### ISSUE TITLE
I get NullReferenceException when ProgressHint

### ISSUE THREAD

**Issue by wdghzym** [syyePhenomenol/RandoMapMod#15]
I get NullReferenceException when i try RandoMapMod3.5.6.ProgressHint on itemsync(no other player)  new game
I try removed all the mods and install RandoMapMod itemsync on Lumafly
I try removed all the GlobalSettings.json
If it's just me, please ignore it

[ERROR]:[UNITY] - NullReferenceException: Object reference not set to an instance of an object
[ERROR]:[UNITY] - RandoMapMod.UI.ProgressHintPanel+<>c__DisplayClass7_0.<UpdateLocation>b__4 (RandomizerMod.RC.ItemPlacement p) (at /Users/Shared/Projects/RandoMapMod/RandoMapMod/UI/WorldMap/TopLeftPanels/ProgressHintPanel.cs:203)
[ERROR]:[UNITY] - System.Linq.Enumerable+WhereEnumerableIterator`1[TSource].MoveNext () (at <55b3683038794c198a24e8a1362bfc61>:0)
[ERROR]:[UNITY] - System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) (at <9577ac7a62ef43179789031239ba8798>:0)
[ERROR]:[UNITY] - RandomizerCore.Extensions.RandomExtensions.Permute[T] (System.Random rand, System.Collections.Generic.IEnumerable`1[T] input) (at C:/dev/RandomizerCore/RandomizerCore/Extensions/RandomExtensions.cs:181)
[ERROR]:[UNITY] - RandoMapMod.UI.ProgressHintPanel.UpdateLocation () (at /Users/Shared/Projects/RandoMapMod/RandoMapMod/UI/WorldMap/TopLeftPanels/ProgressHintPanel.cs:208)
[ERROR]:[UNITY] - RandoMapMod.UI.ProgressHintPanel.UpdateHint () (at /Users/Shared/Projects/RandoMapMod/RandoMapMod/UI/WorldMap/TopLeftPanels/ProgressHintPanel.cs:77)
[ERROR]:[UNITY] - RandoMapMod.UI.Hotkeys+<>c.<BuildLayout>b__1_11 () (at /Users/Shared/Projects/RandoMapMod/RandoMapMod/UI/Hotkeys.cs:88)
[ERROR]:[UNITY] - MagicUI.Behaviours.PlayerActionListener.Update () (at D:/a/HollowKnight.MagicUI/HollowKnight.MagicUI/MagicUI/Behaviours/PlayerActionListener.cs:26)

**Comment by syyePhenomenol** [comment]
Should be fixed in v3.5.7. Thanks for the report
