### ISSUE TITLE
Room Randomizer w/ RandoMapMod considers all rooms out of logic

### ISSUE THREAD

**Issue by Moonkis** [syyePhenomenol/RandoMapMod#16]
I saw there was a few previous reported issues with this but noticed the pathfinding stopped working yesterday, the map was still "correct" (Showcasing visited, reachable, connected and so on). Today when I loaded the save up every room is considered out of logic. All mods *should* be up-to date.

![image](https://github.com/syyePhenomenol/RandoMapMod/assets/1334297/7a865d3a-0949-4748-8922-bb6799b0364d)

Latest (Debug level 1)
[ModLog.txt](https://github.com/user-attachments/files/16119225/ModLog.txt)

From yesterday (Debug level 2):
[ModLog 07 06 2024 (19 00 00).txt](https://github.com/user-attachments/files/16119251/ModLog.07.06.2024.19.00.00.txt)

**Comment by syyePhenomenol** [comment]
Thanks for the report, this should be fixed in v3.5.8

**Comment by Moonkis** [comment]
> Thanks for the report, this should be fixed in v3.5.8

Figured it was the RMM_Waterways_Bench_Floor_2 related, thank you for the quick fix.
