### ISSUE TITLE
[Suggestions] Save settings?

### ISSUE THREAD

**Issue by asimard1** [syyePhenomenol/RandoMapMod#17]
Would it be possible to save the settings to a file in order to load them when a new save file is created?

I prefer to have only the pins and not the whole map and disable the quill, and it would make my life a bit easier if the settings were remembered.

Thank you :)

**Comment by syyePhenomenol** [comment]
Hi there, all of the settings except for map mode and item pools are global settings, which means they carry over to new saves. This should include disabling quill.

Under "Misc Options" in the pause menu there are buttons to set the default map mode for new item rando/transition rando saves.

If this doesn't work as I described please let me know.

**Comment by asimard1** [comment]
Hi, I think the only thing truly missing would be to have a default map mode in general. It defaults to "Full map" for now and I have to change it for every run. (It's not too much of an hassle though, just wondering.)

**Comment by syyePhenomenol** [comment]
`Under "Misc Options" in the pause menu there are buttons to set the default map mode for new item rando/transition rando saves.`

Does this feature do what you described?

**Comment by asimard1** [comment]
Oh I never realized there was a second option for the item rando, I am so sorry! Thank you again for your help with the mod.
