### ISSUE TITLE
Dream bosses are considered out of logic

### ISSUE THREAD

**Issue by Avasam** [syyePhenomenol/RandoMapMod#18]
It looks like because boss essence are "logically" behind defeating bosses, dream bosses show as "unreachable" on the map. In this example, I have dreamnail, nail right, and can trigger/defeat Elder Hu:
![image](https://github.com/user-attachments/assets/3651f453-82f4-40ce-9f1a-36a24c74384a)

I'm not sure whether this is actually an issue with the randomizer or how the Map interprets its logic. Feel free to move this issue if so.

RandoMapMod: 3.5.8.0
Randomizer 4: 4.1.4.1

**Comment by syyePhenomenol** [comment]
This is most likely a logic issue caused by one of the connection mods.

If you want, you can check the logic for "Fungus2_32[left1]" and "Defeated_Elder_Hu" in the RawSpoilerLog.json to see how it might have been modified by a connection mod.

**Comment by Avasam** [comment]
idk exactly what you're looking for, but here's the file. [RawSpoiler.json](https://github.com/user-attachments/files/17196025/RawSpoiler.json)

For completeness sake, here's my entire "Recent" folder: 
[Recent.zip](https://github.com/user-attachments/files/17196077/Recent.zip)

FWIW, I don't have any other rando-related mod other than Archipelago+APMapMod (which hopefully doesn't affect regular Rando4 runs)
Btw I noticed that the logic string the map mod gives is indeed the same as found in the Randomizer source code: https://github.com/homothetyhk/RandomizerMod/blob/e061177fd31332572b5162fc9a767271e71f9291/RandomizerMod/Resources/Logic/locations.json#L716

It seems to imply you need to have beaten the Elder to collect the essence. Which makes sense, but then we're interested in the Elder being reachable, and the map mod tracks the essence itself. If I'm correct, idk if that's just an issue of how the map interprets the requirement, or if it's causing actual logic issues in the randomizer.

**Comment by syyePhenomenol** [comment]
With proficient combat on, Elder Hu combat still requires fireball or wraiths, which you don't seem to have.

For Elder Hu combat to be in logic with no spells, you need to have both proficient combat and difficult skips on.

You can follow the logic here:
https://github.com/homothetyhk/RandomizerMod/blob/e061177fd31332572b5162fc9a767271e71f9291/RandomizerMod/Resources/Logic/macros.json#L177C24-L177C38
https://github.com/homothetyhk/RandomizerMod/blob/e061177fd31332572b5162fc9a767271e71f9291/RandomizerMod/Resources/Logic/macros.json#L144
https://github.com/homothetyhk/RandomizerMod/blob/e061177fd31332572b5162fc9a767271e71f9291/RandomizerMod/Resources/Logic/macros.json#L140
