### ISSUE TITLE
Geo rocks respawn after riding a stag

### ISSUE THREAD

**Issue by Nathan-Carlson** [syyePhenomenol/RandoMapMod#2]
After riding a stag, all geo rocks respawn when reloading a room, including just a screen transition.
Issue still occurs after quitting to main menu and reloading file. Issue does not still occur after exiting the game and reloading, until riding a stag again.
Happens with or without area rando.

**Comment by Nathan-Carlson** [comment]
Does not happen in v3.0.0.
Does happen in v3.0.1 and v3.0.2

**Comment by syyePhenomenol** [comment]
Thanks for the report. Can you send the ModLog.txt file when this occurs?

**Comment by Nathan-Carlson** [comment]
All of the == to is and != to is not should be reverted. They are not the same operators, one is equality and one is pattern matching. That change introduced this bug and probably many others.

**Comment by Nathan-Carlson** [comment]
[ModLog.txt](https://github.com/syyePhenomenol/RandoMapMod/files/9481575/ModLog.txt)

**Comment by syyePhenomenol** [comment]
Yes, thanks for pointing that out, I have changed them back to == and != for all Unity object null checks, which seems to resolve the compass throws
