### ISSUE TITLE
Some minor bugs I found

### ISSUE THREAD

**Issue by argon932** [syyePhenomenol/RandoMapMod#3]
I did a vanilla(ish) playthrough with randomizer and this enabled. I only randomized charm notches and everything else was default. I enabled vanilla tracking on map and did 100% completion.

The following checks do not get marked as completed when collected if not randomized:
Pale Ore Colosseum in Room_Colosseum_01
Charm Notch Colosseum in Room_Colosseum_01
Shopkeeper's Key in Mines_11
Love Key in Fungus3_39
Rancid Egg City of Tears Left in Ruins1_05c (maybe I forgot to pick it up when breaking the nest and then a bug caused it to despawn?)

Thanks.

**Comment by syyePhenomenol** [comment]
If you still have the save, could you share the ModLog, the userX.json file and the userX.modded.json file?

**Comment by argon932** [comment]
Ah, sorry no. I deleted it to make room for a new save after the run.
