### ISSUE TITLE
Room rando: Map mod randomly makes all rooms "out of logic"

### ISSUE THREAD

**Issue by MrPokemon11** [syyePhenomenol/RandoMapMod#6]
At random points in time, the map mod will decide to make all rooms "out of logic, turning everything red and preventing the pathfinder from working correctly. It happens with both chaos room randomizer and normal room randomizer (first and second pictures respectively). This has happened at least 5 times now and is starting to get annoying. If this could get looked into, that would be appreciated. 
![20221003195642_1](https://user-images.githubusercontent.com/53610352/193706256-6b3e277c-0685-4d8f-8622-c54dd08eb295.jpg)
![20220920135428_1](https://user-images.githubusercontent.com/53610352/193706362-946ddcb4-613b-4928-b88e-a30b12321e42.jpg)

**Comment by syyePhenomenol** [comment]
Hi, again it would be nice to have other information such as the ModLog file for me to figure out what is causing this problem. 

Preferably set the debug log level to 1 in the ModdingAPI global settings if you can.

Thanks

**Comment by MrPokemon11** [comment]
Here is the ModLog file you requested. I also set the debug log level to 1, though I'm not sure what that does. The problem appears to be around the end of the file, where MapChangerMod encounters a "NullReferenceException". Hope this helps!
[ModLog.txt](https://github.com/syyePhenomenol/RandoMapMod/files/9706918/ModLog.txt)

**Comment by syyePhenomenol** [comment]
Thanks for the ModLog. It looks like your RandomizerMod is outdated - you need version 4.0.9 for the problem to go away. However I can provide better error handling in future versions of RandoMapMod.
