### ISSUE TITLE
failed to call constructor error with version v3.0.7

### ISSUE THREAD

**Issue by StrykrrX** [syyePhenomenol/RandoMapMod#7]
[ModLog.txt](https://github.com/syyePhenomenol/RandoMapMod/files/10009032/ModLog.txt)

Updated to the most recent version of RanoMapMod through scarab. Have the same error message in the modlog on every launch even after uninstall and reinstall. I manually downgraded to 3.0.6 and the issue disappeared.

**Comment by syyePhenomenol** [comment]
You need MapChanger v1.0.4 to go with RandoMapMod v3.0.7.
